### ISSUE TITLE
Remove the Content-security-Policy

### ISSUE THREAD

**Issue by tlienart** [PTsolvers/GPU4GEO#3]
remove that

https://github.com/PTsolvers/GPU4GEO/blob/5e934f4a7cfc163179cd2a040ce9b5c4d91b1c03/_layout/head.html#L9

that's what causes Safari to block

**Comment by luraess** [comment]
Thanks for posting this ☝️ out.

**Comment by luraess** [comment]
UPDATE: still does not work for me on Safari - also in the Coder example.

**Comment by tlienart** [comment]
so when you do `serve` in the coder example repo, it doesn't load in Safari? which version are you using? this is quite odd. I'm with Safari 15.4. On the positive side, this is not a Xranklin issue; it may be a LiveServer issue but I'm not sure. And removing the GA stuff seemed to help on my side.

**Comment by luraess** [comment]
Hum, weird. I am on 15.4 as well, macOS 10.15.7 (Catalina).

**Comment by luraess** [comment]
UPDATE: seems to work now on Safari after stopping the server and relaunching `serve()`.

**Comment by tlienart** [comment]
Hahaha nice one! Let's hope it stays that way

**Comment by tlienart** [comment]
Hahaha nice one! Let's hope it stays that way
