### ISSUE TITLE
Posts title do not refresh

### ISSUE THREAD

**Issue by luraess** [PTsolvers/GPU4GEO#4]
In the current version, post title do not refresh (locally) unless one removes and adds back the post within the `posts` folder.

**Comment by tlienart** [comment]
can you clarify what you mean? in the coder demo repo I modified the `title = ..` and got immediate change on the page, also on the list. 

Could you check in that bare repo with the same step to see if you get the same problem? (or post screenshots?) thanks!

**Comment by luraess** [comment]
Sorry for that one, seems indeed it gets refreshed as it should. Don't know what went wrong.

**Comment by tlienart** [comment]
I made quite a lot of modifications, it's possible that you updated between two commits, now should be a new "good" state but please keep reporting (and I'll try to be a bit careful with the main branch on Xranklin to avoid hasty fixes that break other stuff).

**Comment by luraess** [comment]
Yeah - may have been a non-final state. Thanks anyway for your rapid support and help 😄. I enjoy working with [X/F]ranklin very much.

**Comment by tlienart** [comment]
great 💯
